Fix debug build: missing initialization in ListHashSet(const ListHashSet&) https://bugs.webkit.org/show_bug.cgi?id=263376
Reviewed by NOBODY (OOPS!).

This fixes this compiler error that is obtained with a vanilla developer
build of trunk:

```
In file included from /webkit/Source/WebCore/Modules/indexeddb/server/UniqueIDBDatabase.h:39,
                 from /webkit/Source/WebCore/Modules/indexeddb/server/UniqueIDBDatabase.cpp:27,
                 from /webkit/WebKitBuild/Debug/WebCore/DerivedSources/unified-sources/UnifiedSource-f8afad56-21.cpp:6:
/webkit/WebKitBuild/Debug/WTF/Headers/wtf/ListHashSet.h: In instantiation of ‘WTF::ListHashSet<Value, HashFunctions>::ListHashSet(const WTF::ListHashSet<Value, HashFunctions>&) [with ValueArg = WTF::RefPtr<WebCore::IDBServer::UniqueIDBDatabaseConnection, WTF::RawPtrTraits<WebCore::IDBServer::UniqueIDBDatabaseConnection>, WTF::DefaultRefDerefTraits<WebCore::IDBServer::UniqueIDBDatabaseConnection> >; HashArg = WTF::DefaultHash<WTF::RefPtr<WebCore::IDBServer::UniqueIDBDatabaseConnection, WTF::RawPtrTraits<WebCore::IDBServer::UniqueIDBDatabaseConnection>, WTF::DefaultRefDerefTraits<WebCore::IDBServer::UniqueIDBDatabaseConnection> > >]’:
/webkit/Source/WebCore/Modules/indexeddb/server/UniqueIDBDatabase.cpp:1456:36:   required from here
/webkit/WebKitBuild/Debug/WTF/Headers/wtf/ListHashSet.h:360:8: error: base class ‘class WTF::CanMakeWeakPtr<WTF::ListHashSet<WTF::RefPtr<WebCore::IDBServer::UniqueIDBDatabaseConnection, WTF::RawPtrTraits<WebCore::IDBServer::UniqueIDBDatabaseConnection>, WTF::DefaultRefDerefTraits<WebCore::IDBServer::UniqueIDBDatabaseConnection> > >, WTF::WeakPtrFactoryInitialization::Eager, WTF::DefaultWeakPtrImpl>’ should be explicitly initialized in the copy constructor [-Werror=extra]
  360 | inline ListHashSet<T, U>::ListHashSet(const ListHashSet& other)
      |        ^~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
[3578/7452] Building CXX object Source/WebCore/CMakeFiles/WebCore.dir/__/__/WebCore/DerivedSources/unified-sources/UnifiedSource-3a52ce78-88.cpp.o
```

* Source/WTF/wtf/ListHashSet.h:
(WTF::U>::ListHashSet):